import { BackgroundImage } from "@/components/background-image";
import { NavbarComponent } from "@/components/navbar/navbar-main";
import { ProvidersWrapper } from "@/components/providers";
import { serverSession } from "@/lib/auth";
import { GetDocumentFontVariables } from "@/lib/styles/fonts";
import "@/lib/styles/globals.css";
import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await serverSession();
  const session = null;

  return (
    <html lang="en">
      <body
        className={`${GetDocumentFontVariables()} antialiased font-primary-body`}
      >
        <ProvidersWrapper session={session}>
          <NavbarComponent />
          {children}
          <BackgroundImage />
        </ProvidersWrapper>
      </body>
    </html>
  );
}
